name: flutter_ai_providers
description: Community-contributed providers for the Flutter AI Toolkit.
version: 0.0.1-dev.1
repository: https://github.com/davidmigloz/flutter_ai_community/tree/main/packages/flutter_ai_providers
issue_tracker: https://github.com/davidmigloz/flutter_ai_community/issues?q=label:p:langgraph

publish_to: 'none'

topics:
  - ai
  - chat
  - llms

environment:
  sdk: ^3.5.0
  flutter: '>=3.27.0'

dependencies:
  anthropic_sdk_dart: ^0.2.0+1
  flutter:
    sdk: flutter
  
  ollama_dart: ^0.2.2+1
  openai_dart: ^0.4.5
  http: ^1.2.2
  flutter_ai_toolkit:
    path: ../../../flutter_ai_toolkit

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
